# Generated by Django 3.0.6 on 2020-05-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommodel',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='custommodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '남자'), ('F', '여자'), ('O', '그 밖의 다른 성')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='custommodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
