# Generated by Django 3.0.6 on 2020-05-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival_m',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='festival_m',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='festival_m',
            name='is_school',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='festival_m',
            name='locate',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='festival_m',
            name='period',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='festival_m',
            name='pub_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='festival_m',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
