# Generated by Django 3.0.6 on 2020-06-04 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festival_m',
            name='period_end',
        ),
    ]
