# Generated by Django 3.0.6 on 2020-06-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0002_auto_20200530_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival_m',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='festival_m',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
