# Generated by Django 3.0.2 on 2020-06-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0003_auto_20200601_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival_m',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='festival/'),
        ),
    ]
