# Generated by Django 3.0.6 on 2020-06-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0003_auto_20200601_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival_m',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='festival/'),
        ),
        migrations.AlterField(
            model_name='festival_m',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
